print("Total bid count cbx: ",bid_count_cbex)
    # print("Total ask count cbx: ",ask_count_cbex)
    # print("Total bid count okx: ",bid_count_okx)
    # print("Total ask count okx: ",ask_count_okx)
    # print("------------------------------------------------------------")